[theme]
primaryColor = "#000000"

backgroundColor = "#000a00"

secondaryBackgroundColor = "#2F4F4F"

textColor = "#ffffff"

[footer]
hideStreamlitIcon = true

[ui]
hideMenu = true  # Oculta el menú de hamburguesa (esquina superior derecha)